# Configuration file for the project
# Tommy Ngx 
# 2021-12-31

# General settings
project_name: "Knee Osteoarthritis Classification"
#output_dir: "/content/outputs" # cpu settings
output_dir: "/projects/OsteoLab/Tommy/KneeOA/Run/outputs" # gpu settings
timezone: "Australia/Sydney"

# Data settings
data:
  #metadata_csv: "/content/dataset/metadata.csv" 
  #metadata_csv: "/projects/OsteoLab/Tommy/KneeOA/Metadata/updated_metadata.csv" # gpu settings
  metadata_csv: "/projects/OsteoLab/Tommy/KneeOA/Metadata/metadata_31dec24.csv" # gpu settings
  #dataset_based_link: "/content/dataset/dataset"
  #dataset_based_link: "/projects/OsteoLab/Tommy/KneeOA/VOS_Phase2/VOS_P2_KNEE_CROP/dataset" # gpu settings
  dataset_based_link: "/projects/OsteoLab/Tommy/KneeOA/Data" # gpu settings
  dataset_name: "VOSP2v2"
  #dataset_name: "VOSP2"
  external_datasets: "OAI16, CGMH" # "None"
  #external_datasets:  "None"
  train_split: "TRAIN"
  val_split: "TEST"
  test_split: "TEST"
  image_path_column: "path_relative"
  label_column: "KL"
  image_size: 224
  batch_size: 32
  num_workers: 2
  class_labels: [0, 1, 2, 3, 4]
  class_names: ["None", "Doubtful", "Mild", "Moderate", "Severe"]
  augmentation: true #false #true
  augmentations:
    horizontal_flip: 
      enabled: true
      p: 0.5
    vertical_flip: 
      enabled: true
      p: 0.5
    rotate: 
      enabled: true
      limit: 45
      p: 0.5
    color_jitter: 
      enabled: true
      brightness: 0.2
      contrast: 0.2
      saturation: 0.2
      hue: 0.2
      p: 0.5
    random_crop: 
      enabled: false
      height: 256
      width: 256
      p: 0.5
    zoom_out:
      enabled: true
      scale_limit: 0.2
      p: 0.5
    normalize: 
      enabled: true
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
      #mean: [0.0, 0.0, 0.0]
      #std: [1.0, 1.0, 1.0]
      p: 1.0
    resize:
      enabled: true
      height: 224
      width: 224

# Model settings
model:
  name: "resnet50"
  pretrained: true

# Training settings
training:
  epochs: 50
  learning_rate: 0.001
  weight_decay: 0.0001
  early_stopping_patience: 100
  lr_scheduler_patience: 50
  batch_size: 32
  optimizer: "Adam"
  evaluation_metrics: ["accuracy", "f1_score"]

# Logging settings
logging:
  log_interval: 10
  save_best_model: true
